/** @type {import('prettier').Config} */
module.exports = {
  endOfLine: "lf",
  semi: false,
  singleQuote: false,
  tabWidth: 2,
  trailingComma: "es5",
  printWidth: 80,
  bracketSpacing: true,
  bracketSameLine: false,
  arrowParens: "always",
  importOrder: [
    "^(react/(.*)$)|^(react$)",
    "^(next/(.*)$)|^(next$)",
    "<THIRD_PARTY_MODULES>",
    "",
    "^types$",
    "^@/env(.*)$",
    "^@/types/(.*)$",
    "^@/constant/(.*)$",
    "^@/config/(.*)$",
    "^@/utils/(.*)$",
    "^@/lib/(.*)$",
    "^@/hooks/(.*)$",
    "^@/components/ui/(.*)$",
    "^@/components/(.*)$",
    "^@/registry/(.*)$",
    "^@/__registry__/(.*)$",
    "^@/styles/(.*)$",
    "^@/app/(.*)$",
    "^@/content/(.*)$",
    "^@/public/(.*)$",
    "^@/scripts/(.*)$",
    "",
    "^[./]",
  ],
  plugins: [
    "@ianvs/prettier-plugin-sort-imports",
    "prettier-plugin-tailwindcss",
  ],
  tailwindAttributes: [
    "titleClassName",
    "descriptionClassName",
    "buttonClasssName",
    "containerClassName",
    "wrapperClassname",
  ],
  tailwindFunctions: ["clsx", "cva", "cn"],
  experimentalTernaries: true,
}
