import { promises as fs } from "fs"
import path from "path"
import { rimraf } from "rimraf"
import { type Registry } from "shadcn/registry"

const registryData = await import("../registry.json")

const registry = registryData.default

async function buildRegistryIndex() {
  let index = `/* eslint-disable @typescript-eslint/ban-ts-comment */
/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react"

export const Index: Record<string, any> = {`
  for (const item of registry.items as Registry["items"]) {
    const resolveFiles = item.files?.map((file) => `${file.path}`)
    if (!resolveFiles) {
      continue
    }

    const componentPath = item.files?.[0]?.path ? `@/${item.files[0].path}` : ""

    index += `
  "${item.name}": {
    name: ${JSON.stringify(item.name)},
    description: ${JSON.stringify(item.description ?? "")},
    type: "${item.type}",
    registryDependencies: ${JSON.stringify(item.registryDependencies)},
    files: [${item.files?.map((file) => {
      const filePath = `${typeof file === "string" ? file : file.path}`
      const resolvedFilePath = path.resolve(filePath)
      return typeof file === "string" ?
          `"${resolvedFilePath}"`
        : `{
      path: "${filePath}",
      type: "${file.type}",
      target: "${file.target ?? ""}"
    }`
    })}],
    component: ${
      componentPath ?
        `React.lazy(async () => {
      const mod = await import("${componentPath}")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    })`
      : "null"
    },
    meta: ${JSON.stringify(item.meta)},
  },`
  }

  index += `
  }`

  // Write style index.
  rimraf.sync(path.join(process.cwd(), "__registry__/index.tsx"))
  await fs.writeFile(path.join(process.cwd(), "__registry__/index.tsx"), index)
}

async function replaceImport() {
  const files = await fs.readdir(path.join(process.cwd(), "public/r"))

  await Promise.all(
    files
      .filter((file) => file.endsWith(".json"))
      .map(async (file) => {
        const content = await fs.readFile(
          path.join(process.cwd(), "public/r", file),
          "utf-8"
        )

        const registryItem = JSON.parse(content)

        // Replace `@/registry/reusables/` in files to `@/components/`
        registryItem.files = registryItem.files?.map((file) => {
          file.content = file.content
            ?.replaceAll("@/registry/reusables/", "@/components/")
            // Handle relative paths to components, hooks, lib, and utils
            .replaceAll(/"\.\.\/reusables\/(.*?)"/g, '"@/components/$1"')
            .replaceAll(/"\.\.\/hooks\/(.*?)"/g, '"@/hooks/$1"')
            .replaceAll(/"\.\.\/lib\/(.*?)"/g, '"@/lib/$1"')
            .replaceAll(/"\.\.\/utils\/(.*?)"/g, '"@/utils/$1"')

          return file
        })

        // Write the file back
        await fs.writeFile(
          path.join(process.cwd(), "public/r", file),
          JSON.stringify(registryItem, null, 2)
        )
      })
  )
}

try {
  console.log("🗂️ Building registry/__index__.tsx...")
  await buildRegistryIndex()
  console.log("🔄 Replacing imports...")
  await replaceImport()
  console.log("✅ Done!")
} catch (error) {
  console.error(error)
  process.exit(1)
}
