/* eslint-disable @typescript-eslint/ban-ts-comment */
/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react"

export const Index: Record<string, any> = {
  "floating-elements": {
    name: "floating-elements",
    description: "",
    type: "registry:component",
    registryDependencies: ["utils"],
    files: [
      {
        path: "registry/reusables/floating-elements.tsx",
        type: "registry:component",
        target: "components/floating-elements.tsx",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/reusables/floating-elements.tsx")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "single-image-upload": {
    name: "single-image-upload",
    description: "",
    type: "registry:component",
    registryDependencies: ["utils"],
    files: [
      {
        path: "registry/reusables/single-image-upload.tsx",
        type: "registry:component",
        target: "components/single-image-upload.tsx",
      },
      {
        path: "hooks/use-file-upload.tsx",
        type: "registry:hook",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/reusables/single-image-upload.tsx")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "multiple-image-upload": {
    name: "multiple-image-upload",
    description: "",
    type: "registry:component",
    registryDependencies: ["utils"],
    files: [
      {
        path: "registry/reusables/multiple-image-upload.tsx",
        type: "registry:component",
        target: "components/multiple-image-upload.tsx",
      },
      {
        path: "hooks/use-multiple-file-upload.tsx",
        type: "registry:hook",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/reusables/multiple-image-upload.tsx")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "multi-file-upload": {
    name: "multi-file-upload",
    description: "",
    type: "registry:component",
    registryDependencies: ["utils"],
    files: [
      {
        path: "registry/reusables/multi-file-upload.tsx",
        type: "registry:component",
        target: "components/multi-file-upload.tsx",
      },
      {
        path: "hooks/use-multiple-file-upload.tsx",
        type: "registry:hook",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/reusables/multi-file-upload.tsx")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "universal-file-upload": {
    name: "universal-file-upload",
    description: "",
    type: "registry:component",
    registryDependencies: ["utils"],
    files: [
      {
        path: "registry/reusables/universal-file-upload.tsx",
        type: "registry:component",
        target: "components/universal-file-upload.tsx",
      },
      {
        path: "hooks/use-multiple-file-upload.tsx",
        type: "registry:hook",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/reusables/universal-file-upload.tsx")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "compact-viewer": {
    name: "compact-viewer",
    description: "",
    type: "registry:component",
    registryDependencies: ["button"],
    files: [
      {
        path: "registry/reusables/pdf-viewers/compact-viewer.tsx",
        type: "registry:component",
        target: "components/pdf-viewers/compact-viewer.tsx",
      },
      {
        path: "registry/reusables/pdf-viewers/loading-spinner.tsx",
        type: "registry:component",
        target: "components/pdf-viewers/loading-spinner.tsx",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/reusables/pdf-viewers/compact-viewer.tsx"
      )
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "fullscreen-viewer": {
    name: "fullscreen-viewer",
    description: "",
    type: "registry:component",
    registryDependencies: ["button"],
    files: [
      {
        path: "registry/reusables/pdf-viewers/fullscreen-viewer.tsx",
        type: "registry:component",
        target: "components/pdf-viewers/fullscreen-viewer.tsx",
      },
      {
        path: "registry/reusables/pdf-viewers/loading-spinner.tsx",
        type: "registry:component",
        target: "components/pdf-viewers/loading-spinner.tsx",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/reusables/pdf-viewers/fullscreen-viewer.tsx"
      )
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "hover-navigation-viewer": {
    name: "hover-navigation-viewer",
    description: "",
    type: "registry:component",
    registryDependencies: ["button"],
    files: [
      {
        path: "registry/reusables/pdf-viewers/hover-navigation-viewer.tsx",
        type: "registry:component",
        target: "components/pdf-viewers/hover-navigation-viewer.tsx",
      },
      {
        path: "registry/reusables/pdf-viewers/loading-spinner.tsx",
        type: "registry:component",
        target: "components/pdf-viewers/loading-spinner.tsx",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/reusables/pdf-viewers/hover-navigation-viewer.tsx"
      )
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "minimal-viewer": {
    name: "minimal-viewer",
    description: "",
    type: "registry:component",
    registryDependencies: ["button"],
    files: [
      {
        path: "registry/reusables/pdf-viewers/minimal-viewer.tsx",
        type: "registry:component",
        target: "components/pdf-viewers/minimal-viewer.tsx",
      },
      {
        path: "registry/reusables/pdf-viewers/loading-spinner.tsx",
        type: "registry:component",
        target: "components/pdf-viewers/loading-spinner.tsx",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/reusables/pdf-viewers/minimal-viewer.tsx"
      )
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "sidebar-viewer": {
    name: "sidebar-viewer",
    description: "",
    type: "registry:component",
    registryDependencies: ["button", "scroll-area"],
    files: [
      {
        path: "registry/reusables/pdf-viewers/sidebar-viewer.tsx",
        type: "registry:component",
        target: "components/pdf-viewers/sidebar-viewer.tsx",
      },
      {
        path: "registry/reusables/pdf-viewers/loading-spinner.tsx",
        type: "registry:component",
        target: "components/pdf-viewers/loading-spinner.tsx",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/reusables/pdf-viewers/sidebar-viewer.tsx"
      )
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "thumbnail-viewer": {
    name: "thumbnail-viewer",
    description: "",
    type: "registry:component",
    registryDependencies: ["button"],
    files: [
      {
        path: "registry/reusables/pdf-viewers/thumbnail-viewer.tsx",
        type: "registry:component",
        target: "components/pdf-viewers/thumbnail-viewer.tsx",
      },
      {
        path: "registry/reusables/pdf-viewers/loading-spinner.tsx",
        type: "registry:component",
        target: "components/pdf-viewers/loading-spinner.tsx",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/reusables/pdf-viewers/thumbnail-viewer.tsx"
      )
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  notify: {
    name: "notify",
    description: "",
    type: "registry:ui",
    registryDependencies: ["utils"],
    files: [
      {
        path: "registry/reusables/ui/notify/notify.tsx",
        type: "registry:ui",
        target: "components/ui/notify/notify.tsx",
      },
      {
        path: "registry/reusables/ui/notify/notify-provider.tsx",
        type: "registry:ui",
        target: "components/ui/notify/notify-provider.tsx",
      },
      {
        path: "registry/reusables/ui/notify/notify-utils.ts",
        type: "registry:ui",
        target: "components/ui/notify/notify-utils.ts",
      },
      {
        path: "registry/reusables/ui/notify/index.ts",
        type: "registry:ui",
        target: "components/ui/notify/index.ts",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/reusables/ui/notify/notify.tsx")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "theme-image": {
    name: "theme-image",
    description: "",
    type: "registry:ui",
    registryDependencies: ["utils"],
    files: [
      {
        path: "registry/reusables/ui/theme-image.tsx",
        type: "registry:ui",
        target: "components/ui/theme-image.tsx",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/reusables/ui/theme-image.tsx")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  spinner: {
    name: "spinner",
    description: "",
    type: "registry:ui",
    registryDependencies: ["utils"],
    files: [
      {
        path: "registry/reusables/ui/spinner.tsx",
        type: "registry:ui",
        target: "components/ui/spinner.tsx",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/reusables/ui/spinner.tsx")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "submit-button": {
    name: "submit-button",
    description: "",
    type: "registry:ui",
    registryDependencies: ["button", "utils"],
    files: [
      {
        path: "registry/reusables/ui/submit-button.tsx",
        type: "registry:ui",
        target: "components/ui/submit-button.tsx",
      },
      {
        path: "registry/reusables/ui/spinner.tsx",
        type: "registry:ui",
        target: "components/ui/spinner.tsx",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/reusables/ui/submit-button.tsx")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "copy-button": {
    name: "copy-button",
    description: "",
    type: "registry:ui",
    registryDependencies: ["button", "utils"],
    files: [
      {
        path: "registry/reusables/ui/copy-button.tsx",
        type: "registry:ui",
        target: "components/ui/copy-button.tsx",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/reusables/ui/copy-button.tsx")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "split-button": {
    name: "split-button",
    description: "",
    type: "registry:ui",
    registryDependencies: ["button", "dropdown-menu", "utils"],
    files: [
      {
        path: "registry/reusables/ui/split-button.tsx",
        type: "registry:ui",
        target: "components/ui/split-button.tsx",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/reusables/ui/split-button.tsx")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "split-button-action": {
    name: "split-button-action",
    description: "",
    type: "registry:ui",
    registryDependencies: ["button", "dropdown-menu", "utils"],
    files: [
      {
        path: "registry/reusables/ui/split-button-action.tsx",
        type: "registry:ui",
        target: "components/ui/split-button-action.tsx",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/reusables/ui/split-button-action.tsx"
      )
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "floating-elements-demo": {
    name: "floating-elements-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["https://reusables.vercel.app/r/floating-elements"],
    files: [
      {
        path: "registry/example/floating-elements-demo.tsx",
        type: "registry:example",
        target: "components/floating-elements-demo.tsx",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/floating-elements-demo.tsx")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "toast-demo": {
    name: "toast-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["https://reusables.vercel.app/r/notify"],
    files: [
      {
        path: "registry/example/toast-demo.tsx",
        type: "registry:example",
        target: "components/toast-demo.tsx",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/toast-demo.tsx")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "time-ago-demo": {
    name: "time-ago-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["https://reusables.vercel.app/r/time-ago"],
    files: [
      {
        path: "registry/example/time-ago-demo.tsx",
        type: "registry:example",
        target: "components/time-ago-demo.tsx",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/time-ago-demo.tsx")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "online-status-demo": {
    name: "online-status-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["https://reusables.vercel.app/r/submit-button"],
    files: [
      {
        path: "registry/example/online-status-demo.tsx",
        type: "registry:example",
        target: "components/online-status-demo.tsx",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/online-status-demo.tsx")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "theme-image-demo": {
    name: "theme-image-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["https://reusables.vercel.app/r/theme-image"],
    files: [
      {
        path: "registry/example/theme-image-demo.tsx",
        type: "registry:example",
        target: "components/theme-image-demo.tsx",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/theme-image-demo.tsx")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "copy-button-demo": {
    name: "copy-button-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["https://reusables.vercel.app/r/copy-button"],
    files: [
      {
        path: "registry/example/copy-button-demo.tsx",
        type: "registry:example",
        target: "components/copy-button-demo.tsx",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/copy-button-demo.tsx")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "submit-button-position-left": {
    name: "submit-button-position-left",
    description: "",
    type: "registry:example",
    registryDependencies: ["https://reusables.vercel.app/r/submit-button"],
    files: [
      {
        path: "registry/example/submit-button-position-left.tsx",
        type: "registry:example",
        target: "components/submit-button-position-left.tsx",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/example/submit-button-position-left.tsx"
      )
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "submit-button-hidetext-demo": {
    name: "submit-button-hidetext-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["https://reusables.vercel.app/r/submit-button"],
    files: [
      {
        path: "registry/example/submit-button-hidetext-demo.tsx",
        type: "registry:example",
        target: "components/submit-button-hidetext-demo.tsx",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/example/submit-button-hidetext-demo.tsx"
      )
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "submit-button-demo": {
    name: "submit-button-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["https://reusables.vercel.app/r/submit-button"],
    files: [
      {
        path: "registry/example/submit-button-demo.tsx",
        type: "registry:example",
        target: "components/submit-button-demo.tsx",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/submit-button-demo.tsx")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "screen-size-demo": {
    name: "screen-size-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["https://reusables.vercel.app/r/use-screen-size"],
    files: [
      {
        path: "registry/example/screen-size-demo.tsx",
        type: "registry:example",
        target: "components/screen-size-demo.tsx",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/screen-size-demo.tsx")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "inview-demo": {
    name: "inview-demo",
    description: "",
    type: "registry:example",
    registryDependencies: [
      "https://reusables.vercel.app/r/use-inview",
      "card",
      "framer-motion",
    ],
    files: [
      {
        path: "registry/example/inview-demo.tsx",
        type: "registry:example",
        target: "components/inview-demo.tsx",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/inview-demo.tsx")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "file-upload-demo": {
    name: "file-upload-demo",
    description: "",
    type: "registry:example",
    registryDependencies: [
      "https://reusables.vercel.app/r/use-file-upload",
      "progress",
      "button",
    ],
    files: [
      {
        path: "registry/example/file-upload-demo.tsx",
        type: "registry:example",
        target: "components/file-upload-demo.tsx",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/file-upload-demo.tsx")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "toast-with-description-demo": {
    name: "toast-with-description-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["https://reusables.vercel.app/r/notify"],
    files: [
      {
        path: "registry/example/toast-with-description-demo.tsx",
        type: "registry:example",
        target: "components/toast-with-description-demo.tsx",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/example/toast-with-description-demo.tsx"
      )
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "toast-positions-demo": {
    name: "toast-positions-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["https://reusables.vercel.app/r/notify"],
    files: [
      {
        path: "registry/example/toast-positions-demo.tsx",
        type: "registry:example",
        target: "components/toast-positions-demo.tsx",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/toast-positions-demo.tsx")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "toast-promise-demo": {
    name: "toast-promise-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["https://reusables.vercel.app/r/notify"],
    files: [
      {
        path: "registry/example/toast-promise-demo.tsx",
        type: "registry:example",
        target: "components/toast-promise-demo.tsx",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/toast-promise-demo.tsx")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "toast-prevent-duplicates-demo": {
    name: "toast-prevent-duplicates-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["https://reusables.vercel.app/r/notify"],
    files: [
      {
        path: "registry/example/toast-prevent-duplicates-demo.tsx",
        type: "registry:example",
        target: "components/toast-prevent-duplicates-demo.tsx",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/example/toast-prevent-duplicates-demo.tsx"
      )
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "toast-custom-config-demo": {
    name: "toast-custom-config-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["https://reusables.vercel.app/r/notify"],
    files: [
      {
        path: "registry/example/toast-custom-config-demo.tsx",
        type: "registry:example",
        target: "components/toast-custom-config-demo.tsx",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/example/toast-custom-config-demo.tsx"
      )
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "toast-progress-demo": {
    name: "toast-progress-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["https://reusables.vercel.app/r/notify"],
    files: [
      {
        path: "registry/example/toast-progress-demo.tsx",
        type: "registry:example",
        target: "components/toast-progress-demo.tsx",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/toast-progress-demo.tsx")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "toast-close-button-demo": {
    name: "toast-close-button-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["https://reusables.vercel.app/r/notify"],
    files: [
      {
        path: "registry/example/toast-close-button-demo.tsx",
        type: "registry:example",
        target: "components/toast-close-button-demo.tsx",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/toast-close-button-demo.tsx")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "split-button-demo": {
    name: "split-button-demo",
    description: "",
    type: "registry:example",
    registryDependencies: [
      "https://reusables.vercel.app/r/split-button",
      "https://reusables.vercel.app/r/notify",
    ],
    files: [
      {
        path: "registry/example/split-button-demo.tsx",
        type: "registry:example",
        target: "components/split-button-demo.tsx",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/split-button-demo.tsx")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "split-button-action-demo": {
    name: "split-button-action-demo",
    description: "",
    type: "registry:example",
    registryDependencies: [
      "https://reusables.vercel.app/r/split-button-action",
      "https://reusables.vercel.app/r/notify",
    ],
    files: [
      {
        path: "registry/example/split-button-action-demo.tsx",
        type: "registry:example",
        target: "components/split-button-action-demo.tsx",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/example/split-button-action-demo.tsx"
      )
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "split-button-preview-demo": {
    name: "split-button-preview-demo",
    description: "",
    type: "registry:example",
    registryDependencies: [
      "https://reusables.vercel.app/r/split-button",
      "https://reusables.vercel.app/r/notify",
    ],
    files: [
      {
        path: "registry/example/split-button-preview-demo.tsx",
        type: "registry:example",
        target: "components/split-button-preview-demo.tsx",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/example/split-button-preview-demo.tsx"
      )
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "direct-image-upload-demo": {
    name: "direct-image-upload-demo",
    description: "",
    type: "registry:example",
    registryDependencies: [
      "https://reusables.vercel.app/r/single-image-upload",
      "https://reusables.vercel.app/r/notify",
    ],
    files: [
      {
        path: "registry/example/direct-image-upload-demo.tsx",
        type: "registry:example",
        target: "components/direct-image-upload-demo.tsx",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/example/direct-image-upload-demo.tsx"
      )
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "manual-image-upload-demo": {
    name: "manual-image-upload-demo",
    description: "",
    type: "registry:example",
    registryDependencies: [
      "shttps://reusables.vercel.app/r/single-image-upload",
      "https://reusables.vercel.app/r/notify",
    ],
    files: [
      {
        path: "registry/example/manual-image-upload-demo.tsx",
        type: "registry:example",
        target: "components/manual-image-upload-demo.tsx",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/example/manual-image-upload-demo.tsx"
      )
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "direct-multiple-image-upload-demo": {
    name: "direct-multiple-image-upload-demo",
    description: "",
    type: "registry:example",
    registryDependencies: [
      "https://reusables.vercel.app/r/multiple-image-upload",
    ],
    files: [
      {
        path: "registry/example/direct-multiple-image-upload-demo.tsx",
        type: "registry:example",
        target: "components/direct-multiple-image-upload-demo.tsx",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/example/direct-multiple-image-upload-demo.tsx"
      )
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "manual-multiple-image-upload-demo": {
    name: "manual-multiple-image-upload-demo",
    description: "",
    type: "registry:example",
    registryDependencies: [
      "https://reusables.vercel.app/r/multiple-image-upload",
    ],
    files: [
      {
        path: "registry/example/manual-multiple-image-upload-demo.tsx",
        type: "registry:example",
        target: "components/manual-multiple-image-upload-demo.tsx",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/example/manual-multiple-image-upload-demo.tsx"
      )
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "multiple-image-upload-form-demo": {
    name: "multiple-image-upload-form-demo",
    description: "",
    type: "registry:example",
    registryDependencies: [
      "https://reusables.vercel.app/r/multiple-image-upload",
      "button",
      "input",
      "form",
      "card",
    ],
    files: [
      {
        path: "registry/example/multiple-image-upload-form-demo.tsx",
        type: "registry:example",
        target: "components/multiple-image-upload-form-demo.tsx",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/example/multiple-image-upload-form-demo.tsx"
      )
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "single-image-upload-form-demo": {
    name: "single-image-upload-form-demo",
    description: "",
    type: "registry:example",
    registryDependencies: [
      "https://reusables.vercel.app/r/single-image-upload",
      "https://reusables.vercel.app/r/notify",
      "button",
      "input",
      "textarea",
      "form",
      "card",
    ],
    files: [
      {
        path: "registry/example/single-image-upload-form-demo.tsx",
        type: "registry:example",
        target: "components/single-image-upload-form-demo.tsx",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/example/single-image-upload-form-demo.tsx"
      )
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "compact-viewer-demo": {
    name: "compact-viewer-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["https://reusables.vercel.app/r/compact-viewer"],
    files: [
      {
        path: "registry/example/compact-viewer-demo.tsx",
        type: "registry:example",
        target: "components/compact-viewer-demo.tsx",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/compact-viewer-demo.tsx")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "fullscreen-viewer-demo": {
    name: "fullscreen-viewer-demo",
    description: "",
    type: "registry:example",
    registryDependencies: [
      "https://reusables.vercel.app/r/fullscreen-viewer",
      "button",
    ],
    files: [
      {
        path: "registry/example/fullscreen-viewer-demo.tsx",
        type: "registry:example",
        target: "components/fullscreen-viewer-demo.tsx",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/fullscreen-viewer-demo.tsx")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "hover-navigation-demo": {
    name: "hover-navigation-demo",
    description: "",
    type: "registry:example",
    registryDependencies: [
      "https://reusables.vercel.app/r/hover-navigation-viewer",
    ],
    files: [
      {
        path: "registry/example/hover-navigation-demo.tsx",
        type: "registry:example",
        target: "components/hover-navigation-demo.tsx",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/hover-navigation-demo.tsx")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "minimal-viewer-demo": {
    name: "minimal-viewer-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["https://reusables.vercel.app/r/minimal-viewer"],
    files: [
      {
        path: "registry/example/minimal-viewer-demo.tsx",
        type: "registry:example",
        target: "components/minimal-viewer-demo.tsx",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/minimal-viewer-demo.tsx")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "sidebar-viewer-demo": {
    name: "sidebar-viewer-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["https://reusables.vercel.app/r/sidebar-viewer"],
    files: [
      {
        path: "registry/example/sidebar-viewer-demo.tsx",
        type: "registry:example",
        target: "components/sidebar-viewer-demo.tsx",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/sidebar-viewer-demo.tsx")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "thumbnail-viewer-demo": {
    name: "thumbnail-viewer-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["https://reusables.vercel.app/r/thumbnail-viewer"],
    files: [
      {
        path: "registry/example/thumbnail-viewer-demo.tsx",
        type: "registry:example",
        target: "components/thumbnail-viewer-demo.tsx",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/thumbnail-viewer-demo.tsx")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "direct-multi-file-upload-demo": {
    name: "direct-multi-file-upload-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["https://reusables.vercel.app/r/multi-file-upload"],
    files: [
      {
        path: "registry/example/direct-multi-file-upload-demo.tsx",
        type: "registry:example",
        target: "components/direct-multi-file-upload-demo.tsx",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/example/direct-multi-file-upload-demo.tsx"
      )
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "manual-multi-file-upload-demo": {
    name: "manual-multi-file-upload-demo",
    description: "",
    type: "registry:example",
    registryDependencies: [
      "https://reusables.vercel.app/r/multi-file-upload",
      "button",
    ],
    files: [
      {
        path: "registry/example/manual-multi-file-upload-demo.tsx",
        type: "registry:example",
        target: "components/manual-multi-file-upload-demo.tsx",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/example/manual-multi-file-upload-demo.tsx"
      )
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "multi-file-upload-form-demo": {
    name: "multi-file-upload-form-demo",
    description: "",
    type: "registry:example",
    registryDependencies: [
      "https://reusables.vercel.app/r/multi-file-upload",
      "https://reusables.vercel.app/r/notify",
      "button",
      "input",
      "form",
      "card",
    ],
    files: [
      {
        path: "registry/example/multi-file-upload-form-demo.tsx",
        type: "registry:example",
        target: "components/multi-file-upload-form-demo.tsx",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/example/multi-file-upload-form-demo.tsx"
      )
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "universal-file-upload-demo": {
    name: "universal-file-upload-demo",
    description: "",
    type: "registry:example",
    registryDependencies: [
      "https://reusables.vercel.app/r/universal-file-upload",
      "https://reusables.vercel.app/r/notify",
      "button",
    ],
    files: [
      {
        path: "registry/example/universal-file-upload-demo.tsx",
        type: "registry:example",
        target: "components/universal-file-upload-demo.tsx",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/example/universal-file-upload-demo.tsx"
      )
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "universal-file-upload-direct-demo": {
    name: "universal-file-upload-direct-demo",
    description: "",
    type: "registry:example",
    registryDependencies: [
      "https://reusables.vercel.app/r/universal-file-upload",
    ],
    files: [
      {
        path: "registry/example/universal-file-upload-direct-demo.tsx",
        type: "registry:example",
        target: "components/universal-file-upload-direct-demo.tsx",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/example/universal-file-upload-direct-demo.tsx"
      )
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "universal-file-upload-form-demo": {
    name: "universal-file-upload-form-demo",
    description: "",
    type: "registry:example",
    registryDependencies: [
      "https://reusables.vercel.app/r/universal-file-upload",
      "button",
      "input",
      "form",
      "card",
    ],
    files: [
      {
        path: "registry/example/universal-file-upload-form-demo.tsx",
        type: "registry:example",
        target: "components/universal-file-upload-form-demo.tsx",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/example/universal-file-upload-form-demo.tsx"
      )
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "time-ago": {
    name: "time-ago",
    description: "",
    type: "registry:lib",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/lib/time-ago.ts",
        type: "registry:lib",
        target: "lib/time-ago.ts",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/lib/time-ago.ts")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  utils: {
    name: "utils",
    description: "",
    type: "registry:lib",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/lib/utils.ts",
        type: "registry:lib",
        target: "lib/utils.ts",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/lib/utils.ts")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "cookies-client": {
    name: "cookies-client",
    description: "",
    type: "registry:lib",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/lib/cookies.client.ts",
        type: "registry:lib",
        target: "lib/cookies.client.ts",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/lib/cookies.client.ts")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "cookies-server": {
    name: "cookies-server",
    description: "",
    type: "registry:lib",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/lib/cookies.server.ts",
        type: "registry:lib",
        target: "lib/cookies.server.ts",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/lib/cookies.server.ts")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  permission: {
    name: "permission",
    description: "",
    type: "registry:lib",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/lib/permission.ts",
        type: "registry:lib",
        target: "lib/permission.ts",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/lib/permission.ts")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "platform-detector": {
    name: "platform-detector",
    description: "",
    type: "registry:lib",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/lib/platform-detector.ts",
        type: "registry:lib",
        target: "lib/platform-detector.ts",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/lib/platform-detector.ts")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
}
