// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react"

export const Index: Record<string, any> = {
  "default": {
    "animated-beam": {
      name: "animated-beam",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["registry/default/reusables/animated-beam.tsx"],
      component: React.lazy(() => import("@/registry/default/reusables/animated-beam.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "animated-gradient-text": {
      name: "animated-gradient-text",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["registry/default/reusables/animated-gradient-text.tsx"],
      component: React.lazy(() => import("@/registry/default/reusables/animated-gradient-text.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "animated-beam-demo": {
      name: "animated-beam-demo",
      type: "registry:example",
      registryDependencies: ["animated-beam"],
      files: ["registry/default/example/animated-beam-demo.tsx"],
      component: React.lazy(() => import("@/registry/default/example/animated-beam-demo.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "animated-beam-bidirectional": {
      name: "animated-beam-bidirectional",
      type: "registry:example",
      registryDependencies: ["animated-beam"],
      files: ["registry/default/example/animated-beam-bidirectional.tsx"],
      component: React.lazy(() => import("@/registry/default/example/animated-beam-bidirectional.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "animated-beam-multiple-outputs": {
      name: "animated-beam-multiple-outputs",
      type: "registry:example",
      registryDependencies: ["animated-beam"],
      files: ["registry/default/example/animated-beam-multiple-outputs.tsx"],
      component: React.lazy(() => import("@/registry/default/example/animated-beam-multiple-outputs.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "animated-beam-multiple-inputs": {
      name: "animated-beam-multiple-inputs",
      type: "registry:example",
      registryDependencies: ["animated-beam"],
      files: ["registry/default/example/animated-beam-multiple-inputs.tsx"],
      component: React.lazy(() => import("@/registry/default/example/animated-beam-multiple-inputs.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "utils": {
      name: "utils",
      type: "registry:lib",
      registryDependencies: undefined,
      files: ["registry/default/lib/utils.ts"],
      component: React.lazy(() => import("@/registry/default/lib/utils.ts")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "cookies-client": {
      name: "cookies-client",
      type: "registry:lib",
      registryDependencies: undefined,
      files: ["registry/default/lib/cookies.client.ts"],
      component: React.lazy(() => import("@/registry/default/lib/cookies.client.ts")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "cookies-server": {
      name: "cookies-server",
      type: "registry:lib",
      registryDependencies: undefined,
      files: ["registry/default/lib/cookies.server.ts"],
      component: React.lazy(() => import("@/registry/default/lib/cookies.server.ts")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "permission": {
      name: "permission",
      type: "registry:lib",
      registryDependencies: undefined,
      files: ["registry/default/lib/permission.ts"],
      component: React.lazy(() => import("@/registry/default/lib/permission.ts")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
  },
}
